language: node_js

matrix:
  include:
    - node_js: "6"
    - node_js: "8"

cache: yarn

before_script:
  - npm install -g yarn

install:
  - yarn run setup

after_script:
  - yarn run coverage

notifications:
  email: false
