version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies-cache-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn run setup

      - save_cache:
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/oc-minify-file/node_modules
            - packages/oc-template-handlebars/node_modules
            - packages/oc-template-handlebars-compiler/node_modules
            - packages/oc-template-jade-compiler/node_modules
            - packages/oc-webpack/node_modules

      - run:
          name: test
          command: yarn test
      - run:
          name: coverage
          command: yarn run coverage
