version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/node:carbon

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies-cache-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn run setup

      - save_cache:
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: test
          command: yarn test

      - run:
          name: coverage
          command: yarn run coverage
